// desktop-vue/src/views/ChatPage.vue
<template>
  <div class="chat-page">
    <div class="chat-header">
      <h2>💬 对话</h2>
      <el-tag :type="wsConnected ? 'success' : 'danger'" size="small">
        {{ wsConnected ? '已连接' : '断开' }}
      </el-tag>
    </div>
    <div class="chat-body" ref="scrollRef">
      <div v-if="!chatStore.messages.length" class="empty-chat">
        <el-icon :size="48"><ChatDotRound /></el-icon>
        <p>开始与智能体对话</p>
      </div>
      <template v-for="msg in chatStore.messages" :key="msg.id">
        <div :class="['msg-row', msg.role]">
          <div class="msg-bubble">{{ msg.content }}</div>
        </div>
        <AwaitHumanCard
          v-if="msg.awaitingHuman"
          :task-id="msg.awaitingHuman.taskId"
          :question="msg.awaitingHuman.question"
        />
      </template>
    </div>
    <div class="chat-input">
      <el-input
        v-model="input"
        placeholder="输入消息..."
        size="large"
        @keyup.enter="send"
      >
        <template #append>
          <el-button type="primary" @click="send"><el-icon><Promotion /></el-icon></el-button>
        </template>
      </el-input>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, nextTick } from 'vue'
import { ChatDotRound, Promotion } from '@element-plus/icons-vue'
import { useChatStore } from '@/stores/chatStore'
import AwaitHumanCard from '@/components/AwaitHumanCard.vue'

const chatStore = useChatStore()
const input = ref('')
const scrollRef = ref<HTMLElement>()
const wsConnected = ref(true)

function send() {
  if (!input.value.trim()) return
  chatStore.sendViaWS(input.value.trim())
  input.value = ''
}

watch(() => chatStore.messages.length, () => {
  nextTick(() => scrollRef.value?.scrollTo({ top: scrollRef.value.scrollHeight, behavior: 'smooth' }))
})
</script>

<style scoped>
.chat-page { height: 100%; display: flex; flex-direction: column; }
.chat-header { display: flex; align-items: center; justify-content: space-between; padding-bottom: 12px; border-bottom: 1px solid #e5e7eb; margin-bottom: 12px; }
.chat-header h2 { font-size: 18px; font-weight: 700; }
.chat-body { flex: 1; overflow-y: auto; padding: 12px; display: flex; flex-direction: column; gap: 8px; }
.empty-chat { text-align: center; color: #9ca3af; margin-top: 60px; }
.msg-row { display: flex; }
.msg-row.user { justify-content: flex-end; }
.msg-bubble { max-width: 75%; padding: 10px 14px; border-radius: 14px; font-size: 14px; line-height: 1.5; }
.msg-row.user .msg-bubble { background: #2563eb; color: #fff; border-bottom-right-radius: 2px; }
.msg-row.assistant .msg-bubble { background: #f3f4f6; color: #374151; border-bottom-left-radius: 2px; }
.chat-input { padding: 12px; border-top: 1px solid #e5e7eb; }
</style>

// desktop/src/pages/ChatPage.tsx
import { useChatStore } from "@/stores/chatStore";
import { useState, useRef, useEffect } from "react";
import { Send, Paperclip, Bot, User } from "lucide-react";

export default function ChatPage() {
  const { messages, sendViaWS } = useChatStore();
  const [input, setInput] = useState("");
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSend = () => {
    if (!input.trim()) return;
    sendViaWS(input.trim());
    setInput("");
  };

  return (
    <div className="h-full flex flex-col max-w-3xl mx-auto">
      <div className="flex items-center gap-2 mb-4 pb-3 border-b">
        <Bot size={20} className="text-blue-600" />
        <h2 className="font-bold text-gray-800">与智能体对话</h2>
        <span className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded-full">在线</span>
      </div>

      <div ref={scrollRef} className="flex-1 overflow-y-auto space-y-4 pb-4">
        {messages.length === 0 && (
          <div className="text-center text-gray-400 mt-20">
            <Bot size={48} className="mx-auto mb-3 opacity-20" />
            <p className="text-lg font-medium mb-1">OpenClaw 智能体</p>
            <p className="text-sm">发送消息开始对话，智能体将自动处理您的任务</p>
          </div>
        )}

        {messages.map((msg) => (
          <div key={msg.id} className={`flex gap-3 ${msg.role === "user" ? "flex-row-reverse" : ""}`}>
            <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${
              msg.role === "user" ? "bg-blue-100 text-blue-600" : "bg-gray-100 text-gray-600"
            }`}>
              {msg.role === "user" ? <User size={16} /> : <Bot size={16} />}
            </div>
            <div className={`max-w-[75%] rounded-lg px-4 py-2.5 text-sm ${
              msg.role === "user"
                ? "bg-blue-600 text-white"
                : "bg-gray-100 text-gray-800"
            }`}>
              {msg.content}
            </div>
          </div>
        ))}
      </div>

      <div className="border-t pt-3">
        <div className="flex items-center gap-2">
          <button className="p-2 text-gray-400 hover:text-gray-600 rounded-full hover:bg-gray-100">
            <Paperclip size={18} />
          </button>
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleSend()}
            placeholder="输入消息..."
            className="flex-1 px-4 py-2.5 border rounded-full text-sm focus:outline-none focus:ring-1 focus:ring-blue-500"
          />
          <button
            onClick={handleSend}
            className="p-2.5 bg-blue-600 text-white rounded-full hover:bg-blue-700 transition-colors"
          >
            <Send size={16} />
          </button>
        </div>
      </div>
    </div>
  );
}
