// desktop-vue/src/views/Dashboard.vue
<template>
  <div class="dashboard">
    <div class="dash-header">
      <div>
        <h2>{{ currentName }}</h2>
        <p class="subtitle">{{ currentDesc }}</p>
      </div>
      <div class="header-actions">
        <el-button :icon="Filter" text>筛选</el-button>
        <el-button type="primary" :icon="Plus" @click="showNewTask = true">新建任务</el-button>
      </div>
    </div>
    <KanbanBoard />

    <el-dialog v-model="showNewTask" title="新建任务" width="500px" destroy-on-close>
      <el-form label-position="top">
        <el-form-item label="任务标题" required>
          <el-input v-model="newTask.title" placeholder="任务标题" @keyup.enter="handleCreate" />
        </el-form-item>
        <el-form-item label="任务描述">
          <el-input v-model="newTask.description" type="textarea" :rows="2" placeholder="任务描述（可选）" />
        </el-form-item>
        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="优先级">
              <el-select v-model="newTask.priority" style="width:100%">
                <el-option label="P0 紧急" value="p0" />
                <el-option label="P1 高" value="p1" />
                <el-option label="P2 中" value="p2" />
                <el-option label="P3 低" value="p3" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="类型">
              <el-select v-model="newTask.type" style="width:100%">
                <el-option label="人工任务" value="human_task" />
                <el-option label="AI 任务" value="ai_task" />
                <el-option label="协作任务" value="mixed" />
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <el-button @click="showNewTask = false">取消</el-button>
        <el-button type="primary" @click="handleCreate" :loading="creating">创建</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, reactive } from 'vue'
import { Plus, Filter } from '@element-plus/icons-vue'
import { useWorkspaceStore } from '@/stores/workspaceStore'
import { useTaskStore } from '@/stores/taskStore'
import KanbanBoard from '@/components/KanbanBoard.vue'

const workspaceStore = useWorkspaceStore()
const taskStore = useTaskStore()
const showNewTask = ref(false)
const creating = ref(false)
const newTask = reactive({ title: '', description: '', priority: 'p2', type: 'human_task' })

const currentName = computed(() => {
  const ws = workspaceStore.workspaces.find(w => w.id === workspaceStore.currentId)
  return (ws?.icon || '📋') + ' ' + (ws?.name || '看板')
})

const currentDesc = computed(() => {
  const ws = workspaceStore.workspaces.find(w => w.id === workspaceStore.currentId)
  return ws?.description || '拖拽卡片变更状态'
})

async function handleCreate() {
  if (!newTask.title.trim()) return
  creating.value = true
  try {
    await taskStore.createTask({
      title: newTask.title.trim(),
      description: newTask.description.trim(),
      priority: newTask.priority,
      type: newTask.type,
      status: 'backlog',
    })
    newTask.title = ''
    newTask.description = ''
    showNewTask.value = false
  } finally {
    creating.value = false
  }
}
</script>

<style scoped>
.dashboard { height: 100%; display: flex; flex-direction: column; }
.dash-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px; }
.dash-header h2 { font-size: 18px; font-weight: 700; color: #111827; }
.subtitle { font-size: 12px; color: #6b7280; margin-top: 2px; }
.header-actions { display: flex; gap: 8px; }
</style>

// desktop/src/pages/Dashboard.tsx
import KanbanBoard from "@/components/KanbanBoard";
import { useTaskStore } from "@/stores/taskStore";
import { useWorkspaceStore } from "@/stores/workspaceStore";
import { Plus, Filter } from "lucide-react";
import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export default function Dashboard() {
  const { workspaces, currentId } = useWorkspaceStore();
  const { createTask } = useTaskStore();
  const current = workspaces.find((w) => w.id === currentId);
  const [showNewTask, setShowNewTask] = useState(false);
  const [newTaskTitle, setNewTaskTitle] = useState("");
  const [newTaskDesc, setNewTaskDesc] = useState("");
  const [newTaskPriority, setNewTaskPriority] = useState("p2");
  const [newTaskType, setNewTaskType] = useState("human_task");
  const [isCreating, setIsCreating] = useState(false);

  const handleCreateTask = async () => {
    if (!newTaskTitle.trim()) return;
    setIsCreating(true);
    try {
      await createTask({
        title: newTaskTitle.trim(),
        description: newTaskDesc.trim(),
        priority: newTaskPriority,
        type: newTaskType,
        status: "backlog",
      });
      setNewTaskTitle("");
      setNewTaskDesc("");
      setNewTaskPriority("p2");
      setNewTaskType("human_task");
      setShowNewTask(false);
    } finally {
      setIsCreating(false);
    }
  };

  return (
    <div className="h-full flex flex-col">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h2 className="text-lg font-bold text-gray-800">
            {current?.icon || "📋"} {current?.name || "看板"}
          </h2>
          <p className="text-xs text-gray-500 mt-0.5">
            {current?.description || "拖拽卡片变更状态"}
          </p>
        </div>
        <div className="flex gap-2">
          <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm border rounded-md hover:bg-gray-50 transition-colors">
            <Filter size={14} />
            筛选
          </button>
          <button
            onClick={() => setShowNewTask(true)}
            className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
          >
            <Plus size={14} />
            新建任务
          </button>
        </div>
      </div>

      <div className="flex-1">
        <KanbanBoard />
      </div>

      <Dialog open={showNewTask} onOpenChange={setShowNewTask}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>新建任务</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <Input
              placeholder="任务标题"
              value={newTaskTitle}
              onChange={(e) => setNewTaskTitle(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && !e.shiftKey && handleCreateTask()}
            />
            <Input
              placeholder="任务描述（可选）"
              value={newTaskDesc}
              onChange={(e) => setNewTaskDesc(e.target.value)}
            />
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1">
                <label className="text-xs text-gray-500">优先级</label>
                <Select value={newTaskPriority} onValueChange={setNewTaskPriority}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="p0">P0 紧急</SelectItem>
                    <SelectItem value="p1">P1 高</SelectItem>
                    <SelectItem value="p2">P2 中</SelectItem>
                    <SelectItem value="p3">P3 低</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1">
                <label className="text-xs text-gray-500">类型</label>
                <Select value={newTaskType} onValueChange={setNewTaskType}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="human_task">人工任务</SelectItem>
                    <SelectItem value="ai_task">AI 任务</SelectItem>
                    <SelectItem value="mixed">协作任务</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="flex justify-end gap-2">
              <Button variant="outline" onClick={() => setShowNewTask(false)} disabled={isCreating}>
                取消
              </Button>
              <Button onClick={handleCreateTask} disabled={!newTaskTitle.trim() || isCreating}>
                {isCreating ? "创建中..." : "创建"}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
