// desktop-vue/src/components/AwaitHumanCard.vue
<template>
  <div class="await-card">
    <div class="await-title">🟡 需要人工确认</div>
    <div class="await-question">{{ question }}</div>
    <div class="await-actions">
      <el-button v-for="opt in options" :key="opt" size="small" type="primary" @click="respond(opt)">
        {{ opt }}
      </el-button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useChatStore } from '@/stores/chatStore'

const props = defineProps<{
  taskId: string
  question: string
  options?: string[]
}>()

const chatStore = useChatStore()
const options = props.options || ['同意', '拒绝', '修改']

function respond(opt: string) {
  chatStore.respondToTask(props.taskId, opt)
}
</script>

<style scoped>
.await-card { background: #fefce8; border: 1px solid #fde047; border-radius: 10px; padding: 12px; }
.await-title { font-size: 13px; font-weight: 600; color: #854d0e; margin-bottom: 6px; }
.await-question { font-size: 13px; color: #713f12; margin-bottom: 10px; }
.await-actions { display: flex; gap: 8px; }
</style>

// desktop/src/components/AwaitHumanCard.tsx
import { useChatStore } from "@/stores/chatStore";
import { AlertTriangle } from "lucide-react";

interface Props {
  taskId: string;
  question: string;
  options?: string[];
}

export default function AwaitHumanCard({ taskId, question, options = ["同意", "拒绝", "修改"] }: Props) {
  const { respondToTask } = useChatStore();

  return (
    <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3 my-2">
      <div className="flex items-start gap-2 mb-2">
        <AlertTriangle size={14} className="text-yellow-500 shrink-0 mt-0.5" />
        <span className="text-sm font-medium text-yellow-800">🟡 等待确认 #{taskId.slice(0, 6)}</span>
      </div>
      <p className="text-sm text-yellow-700 mb-2">{question}</p>
      <div className="flex gap-2">
        {options.map((opt) => (
          <button
            key={opt}
            onClick={() => respondToTask(taskId, opt)}
            className="px-3 py-1 text-xs font-medium rounded-md border border-yellow-300 bg-white hover:bg-yellow-100 text-yellow-800 transition-colors"
          >
            {opt}
          </button>
        ))}
      </div>
    </div>
  );
}
