// desktop-vue/src/components/ChatPanel.vue
<template>
  <teleport to="body">
    <!-- Minimized FAB -->
    <el-button
      v-if="chatStore.isMinimized"
      class="chat-fab"
      circle
      type="primary"
      size="large"
      @click="chatStore.togglePanel"
    >
      <el-icon><ChatDotRound /></el-icon>
      <el-badge v-if="chatStore.unread > 0" :value="chatStore.unread" class="chat-badge" />
    </el-button>

    <!-- Expanded Panel -->
    <div v-else class="chat-panel">
      <div class="panel-header">
        <span>💬 对话</span>
        <div class="header-actions">
          <el-button text size="small" @click="chatStore.minimize"><el-icon><Minus /></el-icon></el-button>
          <el-button text size="small" @click="chatStore.togglePanel"><el-icon><Close /></el-icon></el-button>
        </div>
      </div>

      <div class="panel-body" ref="scrollRef">
        <div v-if="!chatStore.messages.length" class="empty-chat">
          <el-icon :size="32"><ChatDotRound /></el-icon>
          <p>开始与智能体对话</p>
        </div>
        <template v-for="msg in chatStore.messages" :key="msg.id">
          <div :class="['msg-row', msg.role === 'user' ? 'user' : 'assistant']">
            <div class="msg-bubble">{{ msg.content }}</div>
          </div>
          <AwaitHumanCard
            v-if="msg.awaitingHuman"
            :task-id="msg.awaitingHuman.taskId"
            :question="msg.awaitingHuman.question"
          />
        </template>
      </div>

      <div class="panel-footer">
        <el-input
          v-model="input"
          placeholder="输入消息..."
          @keyup.enter="handleSend"
        >
          <template #append>
            <el-button @click="handleSend"><el-icon><Promotion /></el-icon></el-button>
          </template>
        </el-input>
      </div>
    </div>
  </teleport>
</template>

<script setup lang="ts">
import { ref, watch, nextTick } from 'vue'
import { ChatDotRound, Minus, Close, Promotion } from '@element-plus/icons-vue'
import { useChatStore } from '@/stores/chatStore'
import AwaitHumanCard from './AwaitHumanCard.vue'

const chatStore = useChatStore()
const input = ref('')
const scrollRef = ref<HTMLElement>()

function handleSend() {
  if (!input.value.trim()) return
  chatStore.sendViaWS(input.value.trim())
  input.value = ''
}

watch(() => chatStore.messages.length, () => {
  nextTick(() => {
    scrollRef.value?.scrollTo({ top: scrollRef.value.scrollHeight, behavior: 'smooth' })
  })
})
</script>

<style scoped>
.chat-fab { position: fixed; right: 20px; bottom: 20px; width: 52px; height: 52px; z-index: 1000; }
.chat-badge :deep(.el-badge__content) { position: absolute; top: -6px; right: -6px; }
.chat-panel { position: fixed; right: 0; top: 0; bottom: 0; width: 400px; background: #fff; border-left: 1px solid #e5e7eb; display: flex; flex-direction: column; z-index: 1000; box-shadow: -4px 0 12px rgba(0,0,0,0.08); }
.panel-header { display: flex; align-items: center; justify-content: space-between; padding: 10px 14px; border-bottom: 1px solid #e5e7eb; font-weight: 600; font-size: 14px; }
.header-actions { display: flex; gap: 4px; }
.panel-body { flex: 1; overflow-y: auto; padding: 12px; display: flex; flex-direction: column; gap: 8px; }
.empty-chat { text-align: center; color: #9ca3af; margin-top: 40px; }
.msg-row { display: flex; }
.msg-row.user { justify-content: flex-end; }
.msg-bubble { max-width: 80%; padding: 8px 12px; border-radius: 12px; font-size: 13px; line-height: 1.5; word-break: break-word; }
.msg-row.user .msg-bubble { background: #2563eb; color: #fff; border-bottom-right-radius: 2px; }
.msg-row.assistant .msg-bubble { background: #f3f4f6; color: #374151; border-bottom-left-radius: 2px; }
.panel-footer { padding: 10px 12px; border-top: 1px solid #e5e7eb; }
</style>

// desktop/src/components/ChatPanel.tsx
import { useChatStore } from "@/stores/chatStore";
import { useState, useRef, useEffect, useCallback, memo } from "react";
import { MessageSquare, X, Minus, Send, Paperclip } from "lucide-react";
import AwaitHumanCard from "./AwaitHumanCard";

const MessageBubble = memo(function MessageBubble({ msg }: { msg: ReturnType<typeof useChatStore.getState>['messages'][0] }) {
  if (msg.awaitingHuman) {
    return (
      <div className="space-y-2">
        <div className="bg-gray-100 text-gray-800 rounded-lg px-3 py-2 text-sm max-w-[85%]">
          {msg.content}
        </div>
        <AwaitHumanCard
          taskId={msg.awaitingHuman.taskId}
          question={msg.awaitingHuman.question}
          options={msg.awaitingHuman.options}
        />
      </div>
    );
  }
  return (
    <div
      className={`max-w-[85%] rounded-lg px-3 py-2 text-sm ${
        msg.role === "user" ? "bg-blue-600 text-white" : "bg-gray-100 text-gray-800"
      }`}
    >
      {msg.content}
    </div>
  );
});

export default function ChatPanel() {
  const { messages, isMinimized, unread, togglePanel, minimize, sendViaWS } = useChatStore();
  const [input, setInput] = useState("");
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSend = useCallback(() => {
    if (!input.trim()) return;
    sendViaWS(input.trim());
    setInput("");
  }, [input, sendViaWS]);

  if (isMinimized) {
    return (
      <button
        onClick={togglePanel}
        className="fixed right-4 bottom-4 w-12 h-12 bg-blue-600 rounded-full shadow-lg flex items-center justify-center text-white hover:bg-blue-700 transition-colors z-50"
      >
        <MessageSquare size={20} />
        {unread > 0 && (
          <span className="absolute -top-1 -right-1 bg-red-500 text-white text-[10px] w-5 h-5 rounded-full flex items-center justify-center">
            {unread}
          </span>
        )}
      </button>
    );
  }

  return (
    <div className="w-96 bg-white border-l flex flex-col shrink-0 h-full">
      <div className="flex items-center justify-between px-3 py-2 border-b">
        <h3 className="font-semibold text-sm">💬 对话</h3>
        <div className="flex gap-1">
          <button onClick={minimize} className="p-1 hover:bg-gray-100 rounded">
            <Minus size={14} />
          </button>
          <button onClick={togglePanel} className="p-1 hover:bg-gray-100 rounded">
            <X size={14} />
          </button>
        </div>
      </div>

      <div ref={scrollRef} className="flex-1 overflow-y-auto p-3 space-y-3">
        {messages.length === 0 && (
          <div className="text-center text-gray-400 text-sm mt-10">
            <MessageSquare size={32} className="mx-auto mb-2 opacity-30" />
            开始与智能体对话
          </div>
        )}
        {messages.map((msg) => (
          <div key={msg.id} className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}>
            <MessageBubble msg={msg} />
          </div>
        ))}
      </div>

      <div className="border-t p-2">
        <div className="flex items-center gap-2">
          <button className="p-1.5 text-gray-400 hover:text-gray-600">
            <Paperclip size={16} />
          </button>
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleSend()}
            placeholder="输入消息..."
            className="flex-1 text-sm px-3 py-1.5 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500"
          />
          <button
            onClick={handleSend}
            className="p-1.5 bg-blue-600 text-white rounded-md hover:bg-blue-700"
          >
            <Send size={14} />
          </button>
        </div>
      </div>
    </div>
  );
}
