// desktop/src/components/Layout.tsx
import { Outlet, useLocation, useNavigate } from "react-router-dom";
import Sidebar from "./Sidebar";
import ChatPanel from "./ChatPanel";
import { useWorkspaceStore } from "@/stores/workspaceStore";
import { useEffect } from "react";
import { LayoutDashboard, MessageSquare, FileText } from "lucide-react";

export default function Layout() {
  const location = useLocation();
  const navigate = useNavigate();
  const { fetchWorkspaces } = useWorkspaceStore();

  useEffect(() => {
    fetchWorkspaces();
  }, [fetchWorkspaces]);

  const tabs = [
    { path: "/", label: "看板", icon: LayoutDashboard },
    { path: "/chat", label: "对话", icon: MessageSquare },
    { path: "/docs", label: "文档", icon: FileText },
  ];

  return (
    <div className="h-screen flex flex-col bg-gray-50">
      {/* Top Bar */}
      <header className="h-12 bg-white border-b flex items-center px-4 gap-4 shrink-0">
        <div className="font-bold text-lg text-blue-600">OpenClaw</div>
        <nav className="flex gap-1 ml-4">
          {tabs.map((t) => (
            <button
              key={t.path}
              onClick={() => navigate(t.path)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium transition-colors ${
                location.pathname === t.path
                  ? "bg-blue-50 text-blue-600"
                  : "text-gray-600 hover:bg-gray-100"
              }`}
            >
              <t.icon size={16} />
              {t.label}
            </button>
          ))}
        </nav>
      </header>

      {/* Main Content */}
      <div className="flex flex-1 overflow-hidden">
        <Sidebar />
        <main className="flex-1 overflow-auto p-4">
          <Outlet />
        </main>
        <ChatPanel />
      </div>
    </div>
  );
}

// desktop-vue/src/components/Layout.vue
<template>
  <div class="layout">
    <Sidebar />
    <main class="main">
      <nav class="top-nav">
        <router-link to="/" :class="{ active: $route.path === '/' }">📋 看板</router-link>
        <router-link to="/chat" :class="{ active: $route.path === '/chat' }">💬 对话</router-link>
        <router-link to="/docs" :class="{ active: $route.path === '/docs' }">📄 文档</router-link>
      </nav>
      <div class="content">
        <router-view />
      </div>
    </main>
    <ChatPanel />
  </div>
</template>

<script setup lang="ts">
import Sidebar from './Sidebar.vue'
import ChatPanel from './ChatPanel.vue'
</script>

<style scoped>
.layout { display: flex; height: 100vh; }
.main { flex: 1; display: flex; flex-direction: column; min-width: 0; }
.top-nav { display: flex; gap: 8px; padding: 8px 16px; border-bottom: 1px solid #e5e7eb; background: #fff; }
.top-nav a { padding: 6px 16px; border-radius: 6px; font-size: 14px; color: #4b5563; text-decoration: none; transition: all .2s; }
.top-nav a:hover { background: #f3f4f6; }
.top-nav a.active { background: #2563eb; color: #fff; }
.content { flex: 1; padding: 16px; overflow: auto; background: #f9fafb; }
</style>
